services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      -"5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    ports:
      -"8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env

    volumes:
      - postgres_data: